csw:
    registries:
        - id: cswAuscopeTest
          title: "AuScope Test Geonetwork"
          serviceUrl: "http://au-portal-2.it.csiro.au/geonetwork/srv/eng/csw"
          recordInformationUrl: "http://au-portal-2.it.csiro.au/geonetwork/srv/eng/catalog.search#/metadata/%1$s"
        - id: cswAuscopeProduction
          title: "AuScope Geonetwork"
          serviceUrl: "http://portal.auscope.org/geonetwork/srv/eng/csw"
          recordInformationUrl: "http://portal.auscope.org/geonetwork/srv/eng/catalog.search#/metadata/%1$s"
        - id: cswMDUTest
          title: "MDU Test Geonetwork"
          serviceUrl: "http://mdu-data-2.arrc.csiro.au/geonetwork/srv/en/csw"
          recordInformationUrl: "http://mdu-data-2.arrc.csiro.au/geonetwork/srv/en/metadata.show?uuid=%1$s"
        - id: cswMDUProduction
          title: "MDU Geonetwork"
          serviceUrl: "http://mdu-data.arrc.csiro.au/geonetwork/srv/en/csw" 
          recordInformationUrl: "http://mdu-data.arrc.csiro.au/geonetwork/srv/en/main.home?uuid=%1$s"
        - id: cswGAPetroleumTest
          title: "GA Petroleum Geonetwork"
          serviceUrl: "http://auscope-portal-dev.arrc.csiro.au/geonetwork/srv/eng/csw"
          recordInformationUrl: "http://auscope-portal-dev.arrc.csiro.au/geonetwork/srv/eng/main.home?uuid=%1$s"
        - id: cswMRTTest
          title: "Tasmania Test Geonetwork"
          serviceUrl: "http://www.mrt.tas.gov.au/web-catalogue/srv/eng/csw"
          recordInformationUrl: "http://www.mrt.tas.gov.au/web-catalogue/srv/eng/main.home?uuid=%1$s"
        - id: cswMRTProduction 
          title: "Tasmania Geonetwork" 
          serviceUrl: "http://www.mrt.tas.gov.au/web-catalogue/srv/eng/csw"
          recordInformationUrl: "http://www.mrt.tas.gov.au/web-catalogue/srv/eng/main.home?uuid=%1$s"
        - id: cswGAPMDCRC
          title: "Geoscience Australia PMD*CRC Publications" 
          serviceUrl: "http://www.ga.gov.au/geonetwork/srv/en/csw"
          cqlText: "csw:AnyText Like '%PMD*CRC Publication%' AND BBOX(ows:BoundingBox, 110,-9,160,-55)"
          recordInformationUrl: "http://www.ga.gov.au/geonetwork/srv/en/csw?request=GetRecordById&service=CSW&version=2.0.2&OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd&elementSetName=full&id=%1$s"