# This is for developers to set tomcat context path if running from PortalApplication class.
# server:
#     port: 8080
#     servlet:
#         context-path: /AuScope-Portal
        
termsconditions:
   version: 1

spring:
   # Include the registry definitions from application-registries.yaml
   profiles:
       include:
           'registries'
   # Comment out if you're a developer and you don't need to set up a database. 
   # This is to deal with "Failed to configure a datasource" error.
   # autoconfigure:
   #    exclude:
   #        - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration      
env:
    stackdriver:
        enable: false
        project_id: ENTER_GOOGLE_PROJECT_ID
        private_key_id: ENTER_GOOGLE_PRIVATE_KEY_ID
        private_key: ENTER_GOOGLE_PRIVATE_KEY
        client_email: ENTER_CLIENT_EMAIL
        client_id: ENTER_CLIENT_ID
        token_uri: https://oauth2.googleapis.com/token
    twitter:
        enable: false
        consumerKey: ENTER_TWITTER_CONSUMER_KEY
        consumerSecret: ENTER_TWITTER_CONSUMER_SECRET
        accessToken: ENTER_TWITTER_ACCESS_TOKEN
        accessTokenSecret: ENTER_TWITTER_ACCESS_SECRET
        user: AuScope
    vocabService:
        url: http://vocabs.ga.gov.au/cgi/sissvoc/
    nvclVocabService:
        url: http://auscope-services-test.arrc.csiro.au/sissvoc/
    nvclAnalyticalServices:
        url: http://aus-analytical.it.csiro.au/NVCLAnalyticalServices/